# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='enclient',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('entitulo_401', models.CharField(max_length=50, blank=True)),
                ('enimagen401', models.ImageField(upload_to=b'imgs', blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='encontact',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('entitulo_501', models.CharField(max_length=50, blank=True)),
                ('enpregunta51', models.CharField(max_length=50, blank=True)),
                ('enpregunta52', models.EmailField(max_length=50, blank=True)),
                ('enpregunta53', models.CharField(max_length=50, blank=True)),
                ('enpregunta54', models.CharField(max_length=50, blank=True)),
                ('enboton_501', models.CharField(max_length=50, blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='enemballage',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('entitulo_201', models.CharField(max_length=50, blank=True)),
                ('enimagen201', models.ImageField(upload_to=b'imgs', blank=True)),
                ('entext_secundario201', models.TextField(max_length=1000, blank=True)),
                ('enboton_201', models.CharField(max_length=30, blank=True)),
                ('enimagen202', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen203', models.ImageField(upload_to=b'imgs', blank=True)),
                ('entitulo_211', models.CharField(max_length=50, blank=True)),
                ('entext_secundario211', models.TextField(max_length=1000, blank=True)),
                ('entitulo_212', models.CharField(max_length=50, blank=True)),
                ('entext_secundario212', models.TextField(max_length=1000, blank=True)),
                ('entitulo_213', models.CharField(max_length=50, blank=True)),
                ('entext_secundario213', models.TextField(max_length=1000, blank=True)),
                ('enimagen211', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen212', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen213', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen214', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen215', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen216', models.ImageField(upload_to=b'imgs', blank=True)),
                ('entitulo_221', models.CharField(max_length=50, blank=True)),
                ('enempaque_220', models.CharField(max_length=50, blank=True)),
                ('enimagen221', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enempaque_221', models.CharField(max_length=50, blank=True)),
                ('enempaque_222', models.CharField(max_length=50, blank=True)),
                ('enempaque_223', models.CharField(max_length=50, blank=True)),
                ('enempaque_224', models.CharField(max_length=50, blank=True)),
                ('enempaque_225', models.CharField(max_length=50, blank=True)),
                ('enempaque_226', models.CharField(max_length=50, blank=True)),
                ('enempaque_227', models.CharField(max_length=50, blank=True)),
                ('enempaque_228', models.CharField(max_length=50, blank=True)),
                ('enempaque_229', models.CharField(max_length=50, blank=True)),
                ('enempaque_img220', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enempaque_img221', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enempaque_img222', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enempaque_img223', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enempaque_img224', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enempaque_img225', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enempaque_img226', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enempaque_img227', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enempaque_img228', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enempaque_img229', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enflecha', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen231', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen232', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen233', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen234', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen235', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen236', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen237', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen238', models.ImageField(upload_to=b'imgs', blank=True)),
                ('entitulo_241', models.CharField(max_length=50, blank=True)),
                ('enimagen241', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen242', models.ImageField(upload_to=b'imgs', blank=True)),
                ('entitulo_242', models.CharField(max_length=50, blank=True)),
                ('enimagen243', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen244', models.ImageField(upload_to=b'imgs', blank=True)),
                ('entitulo_243', models.CharField(max_length=50, blank=True)),
                ('enimagen245', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen246', models.ImageField(upload_to=b'imgs', blank=True)),
                ('entitulo_251', models.CharField(max_length=50, blank=True)),
                ('ensubtitulo2501', models.CharField(max_length=80, blank=True)),
                ('enimagen2501', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen2502', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen2503', models.ImageField(upload_to=b'imgs', blank=True)),
                ('entext_secundario2501', models.TextField(max_length=1000, blank=True)),
                ('ensubtitulo2502', models.CharField(max_length=80, blank=True)),
                ('enimagen2504', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen2505', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen2506', models.ImageField(upload_to=b'imgs', blank=True)),
                ('entext_secundario2502', models.TextField(max_length=1000, blank=True)),
                ('ensubtitulo2503', models.CharField(max_length=80, blank=True)),
                ('enimagen2507', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen2508', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen2509', models.ImageField(upload_to=b'imgs', blank=True)),
                ('entext_secundario2503', models.TextField(max_length=1000, blank=True)),
                ('ensubtitulo2504', models.CharField(max_length=80, blank=True)),
                ('enimagen2510', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen2511', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen2512', models.ImageField(upload_to=b'imgs', blank=True)),
                ('entext_secundario2504', models.TextField(max_length=1000, blank=True)),
                ('ensubtitulo2505', models.CharField(max_length=80, blank=True)),
                ('enimagen2513', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen2514', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen2515', models.ImageField(upload_to=b'imgs', blank=True)),
                ('entext_secundario2505', models.TextField(max_length=1000, blank=True)),
                ('ensubtitulo2506', models.CharField(max_length=80, blank=True)),
                ('enimagen2516', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen2517', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen2518', models.ImageField(upload_to=b'imgs', blank=True)),
                ('entext_secundario2506', models.TextField(max_length=1000, blank=True)),
                ('ensubtitulo2507', models.CharField(max_length=80, blank=True)),
                ('enimagen2519', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen2520', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen2521', models.ImageField(upload_to=b'imgs', blank=True)),
                ('entext_secundario2507', models.TextField(max_length=1000, blank=True)),
                ('ensubtitulo2508', models.CharField(max_length=80, blank=True)),
                ('enimagen2522', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen2523', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen2524', models.ImageField(upload_to=b'imgs', blank=True)),
                ('entext_secundario2508', models.TextField(max_length=1000, blank=True)),
                ('ensubtitulo2509', models.CharField(max_length=80, blank=True)),
                ('enimagen2525', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen2526', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen2527', models.ImageField(upload_to=b'imgs', blank=True)),
                ('entext_secundario2509', models.TextField(max_length=1000, blank=True)),
                ('ensubtitulo2510', models.CharField(max_length=80, blank=True)),
                ('enimagen2528', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen2529', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen2530', models.ImageField(upload_to=b'imgs', blank=True)),
                ('entext_secundario2510', models.TextField(max_length=1000, blank=True)),
                ('ensubtitulo2511', models.CharField(max_length=80, blank=True)),
                ('enimagen2531', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen2532', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen2533', models.ImageField(upload_to=b'imgs', blank=True)),
                ('entext_secundario2511', models.TextField(max_length=1000, blank=True)),
                ('ensubtitulo2512', models.CharField(max_length=80, blank=True)),
                ('enimagen2534', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen2535', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen2536', models.ImageField(upload_to=b'imgs', blank=True)),
                ('entext_secundario2512', models.TextField(max_length=1000, blank=True)),
                ('ensubtitulo2513', models.CharField(max_length=80, blank=True)),
                ('enimagen2537', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen2538', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen2539', models.ImageField(upload_to=b'imgs', blank=True)),
                ('entext_secundario2513', models.TextField(max_length=1000, blank=True)),
                ('ensubtitulo2514', models.CharField(max_length=80, blank=True)),
                ('enimagen2540', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen2541', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen2542', models.ImageField(upload_to=b'imgs', blank=True)),
                ('entext_secundario2514', models.TextField(max_length=1000, blank=True)),
                ('ensubtitulo2515', models.CharField(max_length=80, blank=True)),
                ('enimagen2543', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen2544', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen2545', models.ImageField(upload_to=b'imgs', blank=True)),
                ('entext_secundario2515', models.TextField(max_length=1000, blank=True)),
                ('enboton_251', models.CharField(max_length=20, blank=True)),
                ('enboton_252', models.CharField(max_length=30, blank=True)),
                ('enimagen251', models.ImageField(upload_to=b'imgs', blank=True)),
                ('encuestionario', models.CharField(max_length=50, blank=True)),
                ('enpregunta21', models.CharField(max_length=50, blank=True)),
                ('enpregunta22', models.EmailField(max_length=50, blank=True)),
                ('enpregunta23', models.CharField(max_length=50, blank=True)),
                ('enpregunta24', models.CharField(max_length=50, blank=True)),
                ('enboton_253', models.CharField(max_length=50, blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='enfooter',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('entitulo_601', models.CharField(max_length=50, blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='enindex',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('enidioma', models.CharField(default=b'es', max_length=2, blank=True, choices=[(b'es', b'Espa\xc3\xb1ol'), (b'en', b'English')])),
                ('encorreo', models.EmailField(max_length=75, blank=True)),
                ('entelf1', models.CharField(max_length=30, blank=True)),
                ('entelf2', models.CharField(max_length=30, blank=True)),
                ('entelf3', models.CharField(max_length=30, blank=True)),
                ('enlogo', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enmenu1', models.CharField(max_length=40, blank=True)),
                ('enmenu2', models.CharField(max_length=40, blank=True)),
                ('enmenu3', models.CharField(max_length=40, blank=True)),
                ('enmenu4', models.CharField(max_length=40, blank=True)),
                ('enmenu5', models.CharField(max_length=40, blank=True)),
                ('enmenu6', models.CharField(max_length=40, blank=True)),
                ('entitulo_111', models.CharField(max_length=50, blank=True)),
                ('entext_secundario111', models.TextField(max_length=1000, blank=True)),
                ('enimagen111', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen112', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen113', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen114', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen115', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen116', models.ImageField(upload_to=b'imgs', blank=True)),
                ('entitulo_121', models.CharField(max_length=50, blank=True)),
                ('entext_secundario121', models.TextField(max_length=1000, blank=True)),
                ('enimagen121', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen122', models.ImageField(upload_to=b'imgs', blank=True)),
                ('entitulo_131', models.CharField(max_length=50, blank=True)),
                ('ensubtitulo131', models.CharField(max_length=80, blank=True)),
                ('entext_secundario131', models.TextField(max_length=1000, blank=True)),
                ('ensubtitulo132', models.CharField(max_length=80, blank=True)),
                ('entext_secundario132', models.TextField(max_length=1000, blank=True)),
                ('enimagen131', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen132', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen133', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen134', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen135', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen136', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen137', models.ImageField(upload_to=b'imgs', blank=True)),
                ('entitulo_141', models.CharField(max_length=50, blank=True)),
                ('entext_secundario141', models.TextField(max_length=1000, blank=True)),
                ('enimagen141', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen142', models.ImageField(upload_to=b'imgs', blank=True)),
                ('entitulo_151', models.CharField(max_length=50, blank=True)),
                ('enimagen151', models.ImageField(upload_to=b'imgs', blank=True)),
                ('entext_secundario151', models.TextField(max_length=1000, blank=True)),
                ('entitulo_152', models.CharField(max_length=50, blank=True)),
                ('enimagen152', models.ImageField(upload_to=b'imgs', blank=True)),
                ('entext_secundario152', models.TextField(max_length=1000, blank=True)),
                ('enimg_certificado', models.ImageField(upload_to=b'imgs', blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='entecnology',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('entitulo_301', models.CharField(max_length=50, blank=True)),
                ('entext_secundario301', models.TextField(max_length=1000, blank=True)),
                ('enboton_301', models.CharField(max_length=30, blank=True)),
                ('enfondo1', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen301', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen302', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ensubtitulo311', models.CharField(max_length=80, blank=True)),
                ('entext_secundario311', models.TextField(max_length=1000, blank=True)),
                ('entext_secundario312', models.TextField(max_length=1000, blank=True)),
                ('entext_secundario313', models.TextField(max_length=1000, blank=True)),
                ('entext_secundario314', models.TextField(max_length=1000, blank=True)),
                ('enimagen311', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enimagen312', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enfondo2', models.ImageField(upload_to=b'imgs', blank=True)),
                ('entext_secundario315', models.TextField(max_length=1000, blank=True)),
                ('entext_secundario316', models.TextField(max_length=1000, blank=True)),
                ('entext_secundario317', models.TextField(max_length=1000, blank=True)),
                ('entext_secundario318', models.TextField(max_length=1000, blank=True)),
                ('entext_secundario319', models.TextField(max_length=1000, blank=True)),
                ('enimagen313', models.ImageField(upload_to=b'imgs', blank=True)),
                ('enfondo3', models.ImageField(upload_to=b'imgs', blank=True)),
                ('entr_top', models.ImageField(upload_to=b'imgs', blank=True)),
                ('entitulo_321', models.CharField(max_length=50, blank=True)),
                ('entext_secundario321', models.TextField(max_length=1000, blank=True)),
                ('entr_bottom', models.ImageField(upload_to=b'imgs', blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
    ]
