# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('titulo_401', models.CharField(max_length=50, blank=True)),
                ('imagen401', models.ImageField(upload_to=b'imgs', blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('titulo_501', models.CharField(max_length=50, blank=True)),
                ('pregunta51', models.CharField(max_length=20, blank=True)),
                ('pregunta52', models.EmailField(max_length=75, blank=True)),
                ('pregunta53', models.CharField(max_length=20, blank=True)),
                ('pregunta54', models.CharField(max_length=50, blank=True)),
                ('boton_501', models.CharField(max_length=20, blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='data_info',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('idioma', models.CharField(default=b'es', max_length=2, blank=True, choices=[(b'en', b'English'), (b'es', b'Espa\xc3\xb1ol')])),
                ('correo', models.EmailField(max_length=75, blank=True)),
                ('telf1', models.CharField(max_length=250, blank=True)),
                ('telf2', models.CharField(max_length=250, blank=True)),
                ('telf3', models.CharField(max_length=250, blank=True)),
                ('logo', models.ImageField(upload_to=b'imgs', blank=True)),
                ('menu1', models.CharField(max_length=20, blank=True)),
                ('menu2', models.CharField(max_length=20, blank=True)),
                ('menu3', models.CharField(max_length=20, blank=True)),
                ('menu4', models.CharField(max_length=20, blank=True)),
                ('menu5', models.CharField(max_length=20, blank=True)),
                ('menu6', models.CharField(max_length=20, blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='emballage',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('titulo_201', models.CharField(max_length=50, blank=True)),
                ('text_secundario201', models.TextField(blank=True)),
                ('boton_201', models.CharField(max_length=20, blank=True)),
                ('imagen201', models.ImageField(upload_to=b'imgs', blank=True)),
                ('titulo_211', models.CharField(max_length=50, blank=True)),
                ('text_secundario211', models.TextField(blank=True)),
                ('titulo_212', models.CharField(max_length=50, blank=True)),
                ('text_secundario212', models.TextField(blank=True)),
                ('titulo_213', models.CharField(max_length=50, blank=True)),
                ('text_secundario213', models.TextField(blank=True)),
                ('imagen211', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen212', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen213', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen214', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen215', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen216', models.ImageField(upload_to=b'imgs', blank=True)),
                ('titulo_221', models.CharField(max_length=50, blank=True)),
                ('empaque_220', models.CharField(max_length=50, blank=True)),
                ('empaque_221', models.CharField(max_length=50, blank=True)),
                ('empaque_222', models.CharField(max_length=50, blank=True)),
                ('empaque_223', models.CharField(max_length=50, blank=True)),
                ('empaque_224', models.CharField(max_length=50, blank=True)),
                ('empaque_225', models.CharField(max_length=50, blank=True)),
                ('empaque_226', models.CharField(max_length=50, blank=True)),
                ('empaque_227', models.CharField(max_length=50, blank=True)),
                ('empaque_228', models.CharField(max_length=50, blank=True)),
                ('empaque_229', models.CharField(max_length=50, blank=True)),
                ('empaque_img220', models.ImageField(upload_to=b'imgs', blank=True)),
                ('empaque_img221', models.ImageField(upload_to=b'imgs', blank=True)),
                ('empaque_img222', models.ImageField(upload_to=b'imgs', blank=True)),
                ('empaque_img223', models.ImageField(upload_to=b'imgs', blank=True)),
                ('empaque_img224', models.ImageField(upload_to=b'imgs', blank=True)),
                ('empaque_img225', models.ImageField(upload_to=b'imgs', blank=True)),
                ('empaque_img226', models.ImageField(upload_to=b'imgs', blank=True)),
                ('empaque_img227', models.ImageField(upload_to=b'imgs', blank=True)),
                ('empaque_img228', models.ImageField(upload_to=b'imgs', blank=True)),
                ('empaque_img229', models.ImageField(upload_to=b'imgs', blank=True)),
                ('titulo_231', models.CharField(max_length=50, blank=True)),
                ('imagen231', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen232', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen233', models.ImageField(upload_to=b'imgs', blank=True)),
                ('titulo_232', models.CharField(max_length=50, blank=True)),
                ('imagen234', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen235', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen236', models.ImageField(upload_to=b'imgs', blank=True)),
                ('titulo_241', models.CharField(max_length=50, blank=True)),
                ('imagen241', models.ImageField(upload_to=b'imgs', blank=True)),
                ('titulo_242', models.CharField(max_length=50, blank=True)),
                ('imagen242', models.ImageField(upload_to=b'imgs', blank=True)),
                ('titulo_243', models.CharField(max_length=50, blank=True)),
                ('imagen243', models.ImageField(upload_to=b'imgs', blank=True)),
                ('titulo_251', models.CharField(max_length=50, blank=True)),
                ('subtitulo2501', models.CharField(max_length=25, blank=True)),
                ('imagen2501', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen2502', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen2503', models.ImageField(upload_to=b'imgs', blank=True)),
                ('text_secundario2501', models.TextField(blank=True)),
                ('subtitulo2502', models.CharField(max_length=25, blank=True)),
                ('imagen2504', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen2505', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen2506', models.ImageField(upload_to=b'imgs', blank=True)),
                ('text_secundario2502', models.TextField(blank=True)),
                ('subtitulo2503', models.CharField(max_length=25, blank=True)),
                ('imagen2507', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen2508', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen2509', models.ImageField(upload_to=b'imgs', blank=True)),
                ('text_secundario2503', models.TextField(blank=True)),
                ('subtitulo2504', models.CharField(max_length=25, blank=True)),
                ('imagen2510', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen2511', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen2512', models.ImageField(upload_to=b'imgs', blank=True)),
                ('text_secundario2504', models.TextField(blank=True)),
                ('subtitulo2505', models.CharField(max_length=25, blank=True)),
                ('imagen2513', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen2514', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen2515', models.ImageField(upload_to=b'imgs', blank=True)),
                ('text_secundario2505', models.TextField(blank=True)),
                ('subtitulo2506', models.CharField(max_length=25, blank=True)),
                ('imagen2516', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen2517', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen2518', models.ImageField(upload_to=b'imgs', blank=True)),
                ('text_secundario2506', models.TextField(blank=True)),
                ('subtitulo2507', models.CharField(max_length=25, blank=True)),
                ('imagen2519', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen2520', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen2521', models.ImageField(upload_to=b'imgs', blank=True)),
                ('text_secundario2507', models.TextField(blank=True)),
                ('subtitulo2508', models.CharField(max_length=25, blank=True)),
                ('imagen2522', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen2523', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen2524', models.ImageField(upload_to=b'imgs', blank=True)),
                ('text_secundario2508', models.TextField(blank=True)),
                ('subtitulo2509', models.CharField(max_length=25, blank=True)),
                ('imagen2525', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen2526', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen2527', models.ImageField(upload_to=b'imgs', blank=True)),
                ('text_secundario2509', models.TextField(blank=True)),
                ('subtitulo2510', models.CharField(max_length=25, blank=True)),
                ('imagen2528', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen2529', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen2530', models.ImageField(upload_to=b'imgs', blank=True)),
                ('text_secundario2510', models.TextField(blank=True)),
                ('subtitulo2511', models.CharField(max_length=25, blank=True)),
                ('imagen2531', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen2532', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen2533', models.ImageField(upload_to=b'imgs', blank=True)),
                ('text_secundario2511', models.TextField(blank=True)),
                ('subtitulo2512', models.CharField(max_length=25, blank=True)),
                ('imagen2534', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen2535', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen2536', models.ImageField(upload_to=b'imgs', blank=True)),
                ('text_secundario2512', models.TextField(blank=True)),
                ('subtitulo2513', models.CharField(max_length=25, blank=True)),
                ('imagen2537', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen2538', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen2539', models.ImageField(upload_to=b'imgs', blank=True)),
                ('text_secundario2513', models.TextField(blank=True)),
                ('subtitulo2514', models.CharField(max_length=25, blank=True)),
                ('imagen2540', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen2541', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen2542', models.ImageField(upload_to=b'imgs', blank=True)),
                ('text_secundario2514', models.TextField(blank=True)),
                ('subtitulo2515', models.CharField(max_length=25, blank=True)),
                ('imagen2543', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen2544', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen2545', models.ImageField(upload_to=b'imgs', blank=True)),
                ('text_secundario2515', models.TextField(blank=True)),
                ('boton_251', models.CharField(max_length=20, blank=True)),
                ('boton_252', models.CharField(max_length=20, blank=True)),
                ('cuestionario', models.CharField(max_length=20, blank=True)),
                ('pregunta21', models.CharField(max_length=20, blank=True)),
                ('pregunta22', models.EmailField(max_length=75, blank=True)),
                ('pregunta23', models.CharField(max_length=20, blank=True)),
                ('pregunta24', models.CharField(max_length=50, blank=True)),
                ('boton_253', models.CharField(max_length=20, blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='footer',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('titulo_601', models.CharField(max_length=50, blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='index',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('titulo_111', models.CharField(max_length=50, blank=True)),
                ('text_secundario111', models.TextField(blank=True)),
                ('imagen111', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen112', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen113', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen114', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen115', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen116', models.ImageField(upload_to=b'imgs', blank=True)),
                ('titulo_121', models.CharField(max_length=50, blank=True)),
                ('text_secundario121', models.TextField(blank=True)),
                ('imagen121', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen122', models.ImageField(upload_to=b'imgs', blank=True)),
                ('titulo_131', models.CharField(max_length=50, blank=True)),
                ('subtitulo131', models.CharField(max_length=25, blank=True)),
                ('text_secundario131', models.TextField(blank=True)),
                ('subtitulo132', models.CharField(max_length=25, blank=True)),
                ('text_secundario132', models.TextField(blank=True)),
                ('imagen131', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen132', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen133', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen134', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen135', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen136', models.ImageField(upload_to=b'imgs', blank=True)),
                ('titulo_141', models.CharField(max_length=50, blank=True)),
                ('text_secundario141', models.TextField(blank=True)),
                ('imagen141', models.ImageField(upload_to=b'imgs', blank=True)),
                ('titulo_151', models.CharField(max_length=50, blank=True)),
                ('text_secundario151', models.TextField(blank=True)),
                ('titulo_152', models.CharField(max_length=50, blank=True)),
                ('text_secundario152', models.TextField(blank=True)),
                ('imagen151', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen152', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen153', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen154', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen155', models.ImageField(upload_to=b'imgs', blank=True)),
                ('imagen156', models.ImageField(upload_to=b'imgs', blank=True)),
                ('img_certificado', models.ImageField(upload_to=b'imgs', blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='tecnology',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('titulo_301', models.CharField(max_length=50, blank=True)),
                ('text_secundario301', models.TextField(blank=True)),
                ('boton_301', models.CharField(max_length=20, blank=True)),
                ('imagen301', models.ImageField(upload_to=b'imgs', blank=True)),
                ('subtitulo311', models.CharField(max_length=25, blank=True)),
                ('text_secundario311', models.TextField(blank=True)),
                ('text_secundario312', models.TextField(blank=True)),
                ('text_secundario313', models.TextField(blank=True)),
                ('text_secundario314', models.TextField(blank=True)),
                ('imagen311', models.ImageField(upload_to=b'imgs', blank=True)),
                ('text_secundario315', models.TextField(blank=True)),
                ('text_secundario316', models.TextField(blank=True)),
                ('text_secundario317', models.TextField(blank=True)),
                ('text_secundario318', models.TextField(blank=True)),
                ('text_secundario319', models.TextField(blank=True)),
                ('imagen312', models.ImageField(upload_to=b'imgs', blank=True)),
                ('titulo_321', models.CharField(max_length=50, blank=True)),
                ('imagen321', models.ImageField(upload_to=b'imgs', blank=True)),
                ('text_secundario321', models.TextField(blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
    ]
