# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emballages', '0005_auto_20160324_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emballage',
            name='boton_201',
            field=models.CharField(max_length=30, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='subtitulo2501',
            field=models.CharField(max_length=80, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='subtitulo2502',
            field=models.CharField(max_length=80, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='subtitulo2503',
            field=models.CharField(max_length=80, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='subtitulo2504',
            field=models.CharField(max_length=80, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='subtitulo2505',
            field=models.CharField(max_length=80, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='subtitulo2506',
            field=models.CharField(max_length=80, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='subtitulo2507',
            field=models.CharField(max_length=80, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='subtitulo2508',
            field=models.CharField(max_length=80, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='subtitulo2509',
            field=models.CharField(max_length=80, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='subtitulo2510',
            field=models.CharField(max_length=80, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='subtitulo2511',
            field=models.CharField(max_length=80, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='subtitulo2512',
            field=models.CharField(max_length=80, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='subtitulo2513',
            field=models.CharField(max_length=80, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='subtitulo2514',
            field=models.CharField(max_length=80, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='subtitulo2515',
            field=models.CharField(max_length=80, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='text_secundario201',
            field=models.TextField(max_length=250, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='text_secundario211',
            field=models.TextField(max_length=250, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='text_secundario212',
            field=models.TextField(max_length=250, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='text_secundario213',
            field=models.TextField(max_length=250, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='text_secundario2501',
            field=models.TextField(max_length=250, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='text_secundario2502',
            field=models.TextField(max_length=250, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='text_secundario2503',
            field=models.TextField(max_length=250, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='text_secundario2504',
            field=models.TextField(max_length=250, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='text_secundario2505',
            field=models.TextField(max_length=250, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='text_secundario2506',
            field=models.TextField(max_length=250, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='text_secundario2507',
            field=models.TextField(max_length=250, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='text_secundario2508',
            field=models.TextField(max_length=250, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='text_secundario2509',
            field=models.TextField(max_length=250, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='text_secundario2510',
            field=models.TextField(max_length=250, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='text_secundario2511',
            field=models.TextField(max_length=250, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='text_secundario2512',
            field=models.TextField(max_length=250, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='text_secundario2513',
            field=models.TextField(max_length=250, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='text_secundario2514',
            field=models.TextField(max_length=250, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='emballage',
            name='text_secundario2515',
            field=models.TextField(max_length=250, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='menu1',
            field=models.CharField(max_length=40, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='menu2',
            field=models.CharField(max_length=40, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='menu3',
            field=models.CharField(max_length=40, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='menu4',
            field=models.CharField(max_length=40, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='menu5',
            field=models.CharField(max_length=40, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='menu6',
            field=models.CharField(max_length=40, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='subtitulo131',
            field=models.CharField(max_length=80, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='subtitulo132',
            field=models.CharField(max_length=80, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='telf1',
            field=models.CharField(max_length=30, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='telf2',
            field=models.CharField(max_length=30, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='telf3',
            field=models.CharField(max_length=30, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='text_secundario111',
            field=models.TextField(max_length=250, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='text_secundario121',
            field=models.TextField(max_length=250, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='text_secundario131',
            field=models.TextField(max_length=250, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='text_secundario132',
            field=models.TextField(max_length=250, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='text_secundario141',
            field=models.TextField(max_length=250, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='text_secundario151',
            field=models.TextField(max_length=250, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='index',
            name='text_secundario152',
            field=models.TextField(max_length=250, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='tecnology',
            name='boton_301',
            field=models.CharField(max_length=30, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='tecnology',
            name='subtitulo311',
            field=models.CharField(max_length=80, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='tecnology',
            name='text_secundario301',
            field=models.TextField(max_length=250, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='tecnology',
            name='text_secundario311',
            field=models.TextField(max_length=250, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='tecnology',
            name='text_secundario312',
            field=models.TextField(max_length=250, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='tecnology',
            name='text_secundario313',
            field=models.TextField(max_length=250, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='tecnology',
            name='text_secundario314',
            field=models.TextField(max_length=250, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='tecnology',
            name='text_secundario315',
            field=models.TextField(max_length=250, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='tecnology',
            name='text_secundario316',
            field=models.TextField(max_length=250, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='tecnology',
            name='text_secundario317',
            field=models.TextField(max_length=250, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='tecnology',
            name='text_secundario318',
            field=models.TextField(max_length=250, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='tecnology',
            name='text_secundario319',
            field=models.TextField(max_length=250, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='tecnology',
            name='text_secundario321',
            field=models.TextField(max_length=250, blank=True),
            preserve_default=True,
        ),
    ]
