#!/usr/bin/python
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
LANGUAGES_CHOICES = (
    ('es', 'Español'),
    ('en', 'English'),
    ('pt', 'Portuguese'),
)


class enindex(models.Model):
	enidioma = models.CharField(blank=True, max_length=2, choices=LANGUAGES_CHOICES, default='es')
	encorreo = models.EmailField(blank=True)
	entelf1 = models.CharField(blank=True, max_length=50)
	entelf2 = models.CharField(blank=True, max_length=50)
	entelf3 = models.CharField(blank=True, max_length=50)
	enlogo = models.ImageField(blank=True, upload_to = 'imgs')
	enmenu1 = models.CharField(blank=True, max_length=40)
	enmenu2 = models.CharField(blank=True, max_length=40)
	enmenu3 = models.CharField(blank=True, max_length=40)
	enmenu4 = models.CharField(blank=True, max_length=40)
	enmenu5 = models.CharField(blank=True, max_length=40)
	enmenu6 = models.CharField(blank=True, max_length=40)

	entitulo_111 = models.CharField(blank=True, max_length=50)
	entext_secundario111 = models.TextField(blank=True, max_length=1000)
	enimagen111 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen112 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen113 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen114 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen115 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen116 = models.ImageField(blank=True, upload_to = 'imgs')

	entitulo_121 = models.CharField(blank=True, max_length=50)
	entext_secundario121 = models.TextField(blank=True, max_length=1000)
	enimagen121 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen122 = models.ImageField(blank=True, upload_to = 'imgs')

	entitulo_131 = models.CharField(blank=True, max_length=50)
        ensubtitulo131 = models.CharField(blank=True, max_length=80)
	entext_secundario131 = models.TextField(blank=True, max_length=1000)
	ensubtitulo132 = models.CharField(blank=True, max_length=80)
	entext_secundario132 = models.TextField(blank=True, max_length=1000)
        enimagen131 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen132 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen133 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen134 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen135 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen136 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen137  = models.ImageField(blank=True, upload_to = 'imgs')

	entitulo_141 = models.CharField(blank=True, max_length=50)
	entext_secundario141 = models.TextField(blank=True, max_length=1000)
	enimagen141 = models.ImageField(blank=True, upload_to = 'imgs')
        enimagen142 = models.ImageField(blank=True, upload_to = 'imgs')

	entitulo_151 = models.CharField(blank=True, max_length=50)
        enimagen151 = models.ImageField(blank=True, upload_to = 'imgs')
	entext_secundario151 = models.TextField(blank=True, max_length=1000)
	entitulo_152 = models.CharField(blank=True, max_length=50)
        enimagen152 = models.ImageField(blank=True, upload_to = 'imgs')
	entext_secundario152 = models.TextField(blank=True, max_length=1000)
	enimg_certificado= models.ImageField(blank=True, upload_to = 'imgs')


	def __unicode__(self):
		return u'%d - %s'%(self.id, self.titulo_111)

class enemballage (models.Model):
	entitulo_201 = models.CharField(blank=True, max_length=50)
        enimagen201 = models.ImageField(blank=True, upload_to = 'imgs')
        entext_secundario201 = models.TextField(blank=True, max_length=1000)
	enboton_201 = models.CharField(blank=True, max_length=30)
	enimagen202 = models.ImageField(blank=True, upload_to = 'imgs')
        enimagen203 = models.ImageField(blank=True, upload_to = 'imgs')

	entitulo_211 = models.CharField(blank=True, max_length=50)
	entext_secundario211 = models.TextField(blank=True, max_length=1000)
	entitulo_212 = models.CharField(blank=True, max_length=50)
	entext_secundario212 = models.TextField(blank=True, max_length=1000)
	entitulo_213 = models.CharField(blank=True, max_length=50)
	entext_secundario213 = models.TextField(blank=True, max_length=1000)
	enimagen211 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen212 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen213 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen214 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen215 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen216 = models.ImageField(blank=True, upload_to = 'imgs')

	entitulo_221 = models.CharField(blank=True, max_length=50)
        enempaque_220 = models.CharField(blank=True, max_length=50)
        enimagen221 = models.ImageField(blank=True, upload_to = 'imgs')
	enempaque_221 = models.CharField(blank=True, max_length=50)
	enempaque_222 = models.CharField(blank=True, max_length=50)
	enempaque_223 = models.CharField(blank=True, max_length=50)
	enempaque_224 = models.CharField(blank=True, max_length=50)
	enempaque_225 = models.CharField(blank=True, max_length=50)
	enempaque_226 = models.CharField(blank=True, max_length=50)
	enempaque_227 = models.CharField(blank=True, max_length=50)
	enempaque_228 = models.CharField(blank=True, max_length=50)
	enempaque_229 = models.CharField(blank=True, max_length=50)
	enempaque_img220 = models.ImageField(blank=True, upload_to = 'imgs')
	enempaque_img221 = models.ImageField(blank=True, upload_to = 'imgs')
	enempaque_img222 = models.ImageField(blank=True, upload_to = 'imgs')
	enempaque_img223 = models.ImageField(blank=True, upload_to = 'imgs')
	enempaque_img224 = models.ImageField(blank=True, upload_to = 'imgs')
	enempaque_img225 = models.ImageField(blank=True, upload_to = 'imgs')
	enempaque_img226 = models.ImageField(blank=True, upload_to = 'imgs')
	enempaque_img227 = models.ImageField(blank=True, upload_to = 'imgs')
	enempaque_img228 = models.ImageField(blank=True, upload_to = 'imgs')
	enempaque_img229 = models.ImageField(blank=True, upload_to = 'imgs')

        enflecha = models.ImageField(blank=True, upload_to = 'imgs')
        enimagen231 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen232 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen233 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen234 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen235 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen236 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen237 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen238 = models.ImageField(blank=True, upload_to = 'imgs')
	entitulo_241 = models.CharField(blank=True, max_length=50)
        enimagen241 = models.ImageField(blank=True, upload_to = 'imgs')
        enimagen242 = models.ImageField(blank=True, upload_to = 'imgs')
	entitulo_242 = models.CharField(blank=True, max_length=50)
        enimagen243 = models.ImageField(blank=True, upload_to = 'imgs')
        enimagen244 = models.ImageField(blank=True, upload_to = 'imgs')
        entitulo_243 = models.CharField(blank=True, max_length=50)
        enimagen245 = models.ImageField(blank=True, upload_to = 'imgs')
        enimagen246 = models.ImageField(blank=True, upload_to = 'imgs')


	entitulo_251 = models.CharField(blank=True, max_length=50)
	ensubtitulo2501 = models.CharField(blank=True, max_length=80)
	enimagen2501 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen2502 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen2503 = models.ImageField(blank=True, upload_to = 'imgs')
	entext_secundario2501 = models.TextField(blank=True, max_length=1000)
	ensubtitulo2502 = models.CharField(blank=True, max_length=80)
	enimagen2504 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen2505 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen2506 = models.ImageField(blank=True, upload_to = 'imgs')
	entext_secundario2502 = models.TextField(blank=True, max_length=1000)
	ensubtitulo2503 = models.CharField(blank=True, max_length=80)
	enimagen2507 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen2508 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen2509 = models.ImageField(blank=True, upload_to = 'imgs')
	entext_secundario2503 = models.TextField(blank=True, max_length=1000)
	ensubtitulo2504 = models.CharField(blank=True, max_length=80)
	enimagen2510 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen2511 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen2512 = models.ImageField(blank=True, upload_to = 'imgs')
	entext_secundario2504 = models.TextField(blank=True, max_length=1000)
	ensubtitulo2505 = models.CharField(blank=True, max_length=80)
	enimagen2513 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen2514 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen2515 = models.ImageField(blank=True, upload_to = 'imgs')
	entext_secundario2505 = models.TextField(blank=True, max_length=1000)
	ensubtitulo2506 = models.CharField(blank=True, max_length=80)
	enimagen2516 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen2517 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen2518 = models.ImageField(blank=True, upload_to = 'imgs')
	entext_secundario2506 = models.TextField(blank=True, max_length=1000)
	ensubtitulo2507 = models.CharField(blank=True, max_length=80)
	enimagen2519 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen2520 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen2521 = models.ImageField(blank=True, upload_to = 'imgs')
	entext_secundario2507 = models.TextField(blank=True, max_length=1000)
	ensubtitulo2508 = models.CharField(blank=True, max_length=80)
	enimagen2522 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen2523 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen2524 = models.ImageField(blank=True, upload_to = 'imgs')
	entext_secundario2508 = models.TextField(blank=True, max_length=1000)
	ensubtitulo2509 = models.CharField(blank=True, max_length=80)
	enimagen2525 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen2526 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen2527 = models.ImageField(blank=True, upload_to = 'imgs')
	entext_secundario2509 = models.TextField(blank=True, max_length=1000)
	ensubtitulo2510 = models.CharField(blank=True, max_length=80)
	enimagen2528 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen2529 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen2530 = models.ImageField(blank=True, upload_to = 'imgs')
	entext_secundario2510 = models.TextField(blank=True, max_length=1000)
	ensubtitulo2511 = models.CharField(blank=True, max_length=80)
	enimagen2531 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen2532 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen2533 = models.ImageField(blank=True, upload_to = 'imgs')
	entext_secundario2511 = models.TextField(blank=True, max_length=1000)
	ensubtitulo2512 = models.CharField(blank=True, max_length=80)
	enimagen2534 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen2535 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen2536 = models.ImageField(blank=True, upload_to = 'imgs')
	entext_secundario2512 = models.TextField(blank=True, max_length=1000)
	ensubtitulo2513 = models.CharField(blank=True, max_length=80)
	enimagen2537 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen2538 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen2539 = models.ImageField(blank=True, upload_to = 'imgs')
	entext_secundario2513 = models.TextField(blank=True, max_length=1000)
	ensubtitulo2514 = models.CharField(blank=True, max_length=80)
	enimagen2540 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen2541 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen2542 = models.ImageField(blank=True, upload_to = 'imgs')
	entext_secundario2514 = models.TextField(blank=True, max_length=1000)
	ensubtitulo2515 = models.CharField(blank=True, max_length=80)
	enimagen2543 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen2544 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen2545 = models.ImageField(blank=True, upload_to = 'imgs')
	entext_secundario2515 = models.TextField(blank=True, max_length=1000)

	enboton_251 = models.CharField(blank=True, max_length=20)
	enboton_252 = models.CharField(blank=True, max_length=30)
        enimagen251 = models.ImageField(blank=True, upload_to = 'imgs')
        encuestionario = models.CharField(blank=True, max_length=50)
    	enpregunta21 = models.CharField(blank=True, max_length=50)
    	enpregunta22 = models.EmailField(blank=True, max_length=50)
    	enpregunta23 = models.CharField(blank=True, max_length=50)
    	enpregunta24 = models.CharField(blank=True, max_length=50)
    	enboton_253 = models.CharField(blank=True, max_length=50)

	def __unicode__(self):
		return u'%d - %s'%(self.id, self.titulo_201)

class entecnology(models.Model):
	entitulo_301 = models.CharField(blank=True, max_length=50)
	entext_secundario301 = models.TextField(blank=True, max_length=1000)
	enboton_301 = models.CharField(blank=True, max_length=30)
        enfondo1 = models.ImageField(blank=True, upload_to = 'imgs')
        enimagen301 = models.ImageField(blank=True, upload_to = 'imgs')
    	enimagen302 = models.ImageField(blank=True, upload_to = 'imgs')

	ensubtitulo311 = models.CharField(blank=True, max_length=80)
	entext_secundario311 = models.TextField(blank=True, max_length=1000)
	entext_secundario312 = models.TextField(blank=True, max_length=1000)
	entext_secundario313 = models.TextField(blank=True, max_length=1000)
	entext_secundario314 = models.TextField(blank=True, max_length=1000)
	enimagen311 = models.ImageField(blank=True, upload_to = 'imgs')
	enimagen312 = models.ImageField(blank=True, upload_to = 'imgs')
        enfondo2 = models.ImageField(blank=True, upload_to = 'imgs')
        entext_secundario315 = models.TextField(blank=True, max_length=1000)
    	entext_secundario316 = models.TextField(blank=True, max_length=1000)
    	entext_secundario317 = models.TextField(blank=True, max_length=1000)
    	entext_secundario318 = models.TextField(blank=True, max_length=1000)
    	entext_secundario319 = models.TextField(blank=True, max_length=1000)
    	enimagen313 = models.ImageField(blank=True, upload_to = 'imgs')
        enfondo3 = models.ImageField(blank=True, upload_to = 'imgs')
        entr_top = models.ImageField(blank=True, upload_to = 'imgs')
    	entitulo_321 = models.CharField(blank=True, max_length=50)
        entext_secundario321 = models.TextField(blank=True, max_length=1000)
    	entr_bottom = models.ImageField(blank=True, upload_to = 'imgs')

	def __unicode__(self):
		return u'%d - %s'%(self.id, self.titulo_301)

class enclient(models.Model):
	entitulo_401 = models.CharField(blank=True, max_length=50)
	enimagen401 = models.ImageField(blank=True, upload_to = 'imgs')

	def __unicode__(self):
		return u'%d - %s'%(self.id, self.titulo_401)

class encontact(models.Model):
	entitulo_501 = models.CharField(blank=True, max_length=50)
	enpregunta51 = models.CharField(blank=True, max_length=50)
	enpregunta52 = models.EmailField(blank=True, max_length=50)
	enpregunta53 = models.CharField(blank=True, max_length=50)
	enpregunta54 = models.CharField(blank=True, max_length=50)
	enboton_501 = models.CharField(blank=True, max_length=50)

	def __unicode__(self):
		return u'%d - %s'%(self.id, self.titulo_501)

class enfooter(models.Model):
	entitulo_601 = models.CharField(blank=True,  max_length=50)

	def __unicode__(self):
		return u'%d - %s'%(self.id, self.titulo_601)
