# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ptclient',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('pttitulo_401', models.CharField(max_length=50, blank=True)),
                ('ptimagen401', models.ImageField(upload_to=b'imgs', blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ptcontact',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('pttitulo_501', models.CharField(max_length=50, blank=True)),
                ('ptpregunta51', models.CharField(max_length=50, blank=True)),
                ('ptpregunta52', models.EmailField(max_length=50, blank=True)),
                ('ptpregunta53', models.CharField(max_length=50, blank=True)),
                ('ptpregunta54', models.CharField(max_length=50, blank=True)),
                ('ptboton_501', models.CharField(max_length=50, blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ptemballage',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('pttitulo_201', models.CharField(max_length=50, blank=True)),
                ('ptimagen201', models.ImageField(upload_to=b'imgs', blank=True)),
                ('pttext_secundario201', models.TextField(max_length=1000, blank=True)),
                ('ptboton_201', models.CharField(max_length=30, blank=True)),
                ('ptimagen202', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen203', models.ImageField(upload_to=b'imgs', blank=True)),
                ('pttitulo_211', models.CharField(max_length=50, blank=True)),
                ('pttext_secundario211', models.TextField(max_length=1000, blank=True)),
                ('pttitulo_212', models.CharField(max_length=50, blank=True)),
                ('pttext_secundario212', models.TextField(max_length=1000, blank=True)),
                ('pttitulo_213', models.CharField(max_length=50, blank=True)),
                ('pttext_secundario213', models.TextField(max_length=1000, blank=True)),
                ('ptimagen211', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen212', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen213', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen214', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen215', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen216', models.ImageField(upload_to=b'imgs', blank=True)),
                ('pttitulo_221', models.CharField(max_length=50, blank=True)),
                ('ptempaque_220', models.CharField(max_length=50, blank=True)),
                ('ptimagen221', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptempaque_221', models.CharField(max_length=50, blank=True)),
                ('ptempaque_222', models.CharField(max_length=50, blank=True)),
                ('ptempaque_223', models.CharField(max_length=50, blank=True)),
                ('ptempaque_224', models.CharField(max_length=50, blank=True)),
                ('ptempaque_225', models.CharField(max_length=50, blank=True)),
                ('ptempaque_226', models.CharField(max_length=50, blank=True)),
                ('ptempaque_227', models.CharField(max_length=50, blank=True)),
                ('ptempaque_228', models.CharField(max_length=50, blank=True)),
                ('ptempaque_229', models.CharField(max_length=50, blank=True)),
                ('ptempaque_img220', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptempaque_img221', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptempaque_img222', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptempaque_img223', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptempaque_img224', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptempaque_img225', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptempaque_img226', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptempaque_img227', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptempaque_img228', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptempaque_img229', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptflecha', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen231', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen232', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen233', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen234', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen235', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen236', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen237', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen238', models.ImageField(upload_to=b'imgs', blank=True)),
                ('pttitulo_241', models.CharField(max_length=50, blank=True)),
                ('ptimagen241', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen242', models.ImageField(upload_to=b'imgs', blank=True)),
                ('pttitulo_242', models.CharField(max_length=50, blank=True)),
                ('ptimagen243', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen244', models.ImageField(upload_to=b'imgs', blank=True)),
                ('pttitulo_243', models.CharField(max_length=50, blank=True)),
                ('ptimagen245', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen246', models.ImageField(upload_to=b'imgs', blank=True)),
                ('pttitulo_251', models.CharField(max_length=50, blank=True)),
                ('ptsubtitulo2501', models.CharField(max_length=80, blank=True)),
                ('ptimagen2501', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen2502', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen2503', models.ImageField(upload_to=b'imgs', blank=True)),
                ('pttext_secundario2501', models.TextField(max_length=1000, blank=True)),
                ('ptsubtitulo2502', models.CharField(max_length=80, blank=True)),
                ('ptimagen2504', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen2505', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen2506', models.ImageField(upload_to=b'imgs', blank=True)),
                ('pttext_secundario2502', models.TextField(max_length=1000, blank=True)),
                ('ptsubtitulo2503', models.CharField(max_length=80, blank=True)),
                ('ptimagen2507', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen2508', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen2509', models.ImageField(upload_to=b'imgs', blank=True)),
                ('pttext_secundario2503', models.TextField(max_length=1000, blank=True)),
                ('ptsubtitulo2504', models.CharField(max_length=80, blank=True)),
                ('ptimagen2510', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen2511', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen2512', models.ImageField(upload_to=b'imgs', blank=True)),
                ('pttext_secundario2504', models.TextField(max_length=1000, blank=True)),
                ('ptsubtitulo2505', models.CharField(max_length=80, blank=True)),
                ('ptimagen2513', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen2514', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen2515', models.ImageField(upload_to=b'imgs', blank=True)),
                ('pttext_secundario2505', models.TextField(max_length=1000, blank=True)),
                ('ptsubtitulo2506', models.CharField(max_length=80, blank=True)),
                ('ptimagen2516', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen2517', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen2518', models.ImageField(upload_to=b'imgs', blank=True)),
                ('pttext_secundario2506', models.TextField(max_length=1000, blank=True)),
                ('ptsubtitulo2507', models.CharField(max_length=80, blank=True)),
                ('ptimagen2519', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen2520', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen2521', models.ImageField(upload_to=b'imgs', blank=True)),
                ('pttext_secundario2507', models.TextField(max_length=1000, blank=True)),
                ('ptsubtitulo2508', models.CharField(max_length=80, blank=True)),
                ('ptimagen2522', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen2523', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen2524', models.ImageField(upload_to=b'imgs', blank=True)),
                ('pttext_secundario2508', models.TextField(max_length=1000, blank=True)),
                ('ptsubtitulo2509', models.CharField(max_length=80, blank=True)),
                ('ptimagen2525', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen2526', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen2527', models.ImageField(upload_to=b'imgs', blank=True)),
                ('pttext_secundario2509', models.TextField(max_length=1000, blank=True)),
                ('ptsubtitulo2510', models.CharField(max_length=80, blank=True)),
                ('ptimagen2528', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen2529', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen2530', models.ImageField(upload_to=b'imgs', blank=True)),
                ('pttext_secundario2510', models.TextField(max_length=1000, blank=True)),
                ('ptsubtitulo2511', models.CharField(max_length=80, blank=True)),
                ('ptimagen2531', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen2532', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen2533', models.ImageField(upload_to=b'imgs', blank=True)),
                ('pttext_secundario2511', models.TextField(max_length=1000, blank=True)),
                ('ptsubtitulo2512', models.CharField(max_length=80, blank=True)),
                ('ptimagen2534', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen2535', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen2536', models.ImageField(upload_to=b'imgs', blank=True)),
                ('pttext_secundario2512', models.TextField(max_length=1000, blank=True)),
                ('ptsubtitulo2513', models.CharField(max_length=80, blank=True)),
                ('ptimagen2537', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen2538', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen2539', models.ImageField(upload_to=b'imgs', blank=True)),
                ('pttext_secundario2513', models.TextField(max_length=1000, blank=True)),
                ('ptsubtitulo2514', models.CharField(max_length=80, blank=True)),
                ('ptimagen2540', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen2541', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen2542', models.ImageField(upload_to=b'imgs', blank=True)),
                ('pttext_secundario2514', models.TextField(max_length=1000, blank=True)),
                ('ptsubtitulo2515', models.CharField(max_length=80, blank=True)),
                ('ptimagen2543', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen2544', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen2545', models.ImageField(upload_to=b'imgs', blank=True)),
                ('pttext_secundario2515', models.TextField(max_length=1000, blank=True)),
                ('ptboton_251', models.CharField(max_length=20, blank=True)),
                ('ptboton_252', models.CharField(max_length=30, blank=True)),
                ('ptimagen251', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptcuestionario', models.CharField(max_length=50, blank=True)),
                ('ptpregunta21', models.CharField(max_length=50, blank=True)),
                ('ptpregunta22', models.EmailField(max_length=50, blank=True)),
                ('ptpregunta23', models.CharField(max_length=50, blank=True)),
                ('ptpregunta24', models.CharField(max_length=50, blank=True)),
                ('ptboton_253', models.CharField(max_length=50, blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ptfooter',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('pttitulo_601', models.CharField(max_length=50, blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ptindex',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('ptidioma', models.CharField(default=b'es', max_length=2, blank=True, choices=[(b'es', b'Espa\xc3\xb1ol'), (b'en', b'English'), (b'pt', b'Portuguese')])),
                ('ptcorreo', models.EmailField(max_length=75, blank=True)),
                ('pttelf1', models.CharField(max_length=30, blank=True)),
                ('pttelf2', models.CharField(max_length=30, blank=True)),
                ('pttelf3', models.CharField(max_length=30, blank=True)),
                ('ptlogo', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptmenu1', models.CharField(max_length=40, blank=True)),
                ('ptmenu2', models.CharField(max_length=40, blank=True)),
                ('ptmenu3', models.CharField(max_length=40, blank=True)),
                ('ptmenu4', models.CharField(max_length=40, blank=True)),
                ('ptmenu5', models.CharField(max_length=40, blank=True)),
                ('ptmenu6', models.CharField(max_length=40, blank=True)),
                ('pttitulo_111', models.CharField(max_length=50, blank=True)),
                ('pttext_secundario111', models.TextField(max_length=1000, blank=True)),
                ('ptimagen111', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen112', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen113', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen114', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen115', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen116', models.ImageField(upload_to=b'imgs', blank=True)),
                ('pttitulo_121', models.CharField(max_length=50, blank=True)),
                ('pttext_secundario121', models.TextField(max_length=1000, blank=True)),
                ('ptimagen121', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen122', models.ImageField(upload_to=b'imgs', blank=True)),
                ('pttitulo_131', models.CharField(max_length=50, blank=True)),
                ('ptsubtitulo131', models.CharField(max_length=80, blank=True)),
                ('pttext_secundario131', models.TextField(max_length=1000, blank=True)),
                ('ptsubtitulo132', models.CharField(max_length=80, blank=True)),
                ('pttext_secundario132', models.TextField(max_length=1000, blank=True)),
                ('ptimagen131', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen132', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen133', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen134', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen135', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen136', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen137', models.ImageField(upload_to=b'imgs', blank=True)),
                ('pttitulo_141', models.CharField(max_length=50, blank=True)),
                ('pttext_secundario141', models.TextField(max_length=1000, blank=True)),
                ('ptimagen141', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen142', models.ImageField(upload_to=b'imgs', blank=True)),
                ('pttitulo_151', models.CharField(max_length=50, blank=True)),
                ('ptimagen151', models.ImageField(upload_to=b'imgs', blank=True)),
                ('pttext_secundario151', models.TextField(max_length=1000, blank=True)),
                ('pttitulo_152', models.CharField(max_length=50, blank=True)),
                ('ptimagen152', models.ImageField(upload_to=b'imgs', blank=True)),
                ('pttext_secundario152', models.TextField(max_length=1000, blank=True)),
                ('ptimg_certificado', models.ImageField(upload_to=b'imgs', blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='pttecnology',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('pttitulo_301', models.CharField(max_length=50, blank=True)),
                ('pttext_secundario301', models.TextField(max_length=1000, blank=True)),
                ('ptboton_301', models.CharField(max_length=30, blank=True)),
                ('ptfondo1', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen301', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen302', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptsubtitulo311', models.CharField(max_length=80, blank=True)),
                ('pttext_secundario311', models.TextField(max_length=1000, blank=True)),
                ('pttext_secundario312', models.TextField(max_length=1000, blank=True)),
                ('pttext_secundario313', models.TextField(max_length=1000, blank=True)),
                ('pttext_secundario314', models.TextField(max_length=1000, blank=True)),
                ('ptimagen311', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptimagen312', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptfondo2', models.ImageField(upload_to=b'imgs', blank=True)),
                ('pttext_secundario315', models.TextField(max_length=1000, blank=True)),
                ('pttext_secundario316', models.TextField(max_length=1000, blank=True)),
                ('pttext_secundario317', models.TextField(max_length=1000, blank=True)),
                ('pttext_secundario318', models.TextField(max_length=1000, blank=True)),
                ('pttext_secundario319', models.TextField(max_length=1000, blank=True)),
                ('ptimagen313', models.ImageField(upload_to=b'imgs', blank=True)),
                ('ptfondo3', models.ImageField(upload_to=b'imgs', blank=True)),
                ('pttr_top', models.ImageField(upload_to=b'imgs', blank=True)),
                ('pttitulo_321', models.CharField(max_length=50, blank=True)),
                ('pttext_secundario321', models.TextField(max_length=1000, blank=True)),
                ('pttr_bottom', models.ImageField(upload_to=b'imgs', blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
    ]
